package Frontend;

import Frontend.MainMenu;
import Frontend.Login;
import Business.ThreadOrnek;
import Business.Business;
import entities.Data;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author mirac
 */
public class ResultDoubleFilter extends javax.swing.JDialog {
    DefaultTableModel model;
    Business business = new Business();
    /**
     * Creates new form ResultDoubleFilter
     */
    public ResultDoubleFilter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel)tablo.getModel();
        UrunleriGoruntule();
    }
    
    public void UrunleriGoruntule(){
        model.setRowCount(0);
        business.AramaGenel(Login.veriler, MainMenu.threadSayisi,100,2); // aynı ürünler bulundu
        ArrayList<Data> veriSeti = new ArrayList<Data>();
        veriSeti = (ArrayList)ThreadOrnek.result.clone();
        
        ThreadOrnek.result.clear();
        
        business.AramaGenel(veriSeti, MainMenu.threadSayisi , MainMenu.miktar, MainMenu.sutun);
        
        if(ThreadOrnek.result != null){
            switch (MainMenu.gosterilecekSutun) {
                case 3:
                    for(Data data : ThreadOrnek.result){
                        Object[] eklenecek = {data.getId(),data.getProduct(),data.getIssue()};
                        if(model.getRowCount() == 25000){
                            break;
                        }
                        model.addRow(eklenecek);
                    }
                    break;
                case 4:
                    for(Data data : ThreadOrnek.result){
                        Object[] eklenecek = {data.getId(),data.getProduct(),data.getCompany()};
                        if(model.getRowCount() == 25000){
                            break;
                        }
                        model.addRow(eklenecek);
                    }
                    break;
                case 5:
                    for(Data data : ThreadOrnek.result){
                        Object[] eklenecek = {data.getId(),data.getProduct(),data.getState()};
                        if(model.getRowCount() == 25000){
                            break;
                        }
                        model.addRow(eklenecek);
                    }
                    break;
                default:
                    throw new AssertionError();
            }
        }
        
        LabelSure.setText(String.valueOf(Business.sure));
        Veri_sayisi.setText(String.valueOf(ThreadOrnek.result.size()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Veri_sayisi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sure = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonCikis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        TextSure = new javax.swing.JLabel();
        LabelSure = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Products");
        setBounds(new java.awt.Rectangle(600, 400, 0, 0));

        jLabel1.setText("Veri sayısı :");

        jLabel2.setText("Süre : ");

        jLabel3.setText("saniye");

        ButtonCikis.setBackground(new java.awt.Color(255, 102, 102));
        ButtonCikis.setText("Çıkış");
        ButtonCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCikisActionPerformed(evt);
            }
        });

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablo);
        if (tablo.getColumnModel().getColumnCount() > 0) {
            tablo.getColumnModel().getColumn(0).setResizable(false);
            tablo.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Veri_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sure, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelSure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(TextSure)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(ButtonCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Veri_sayisi)
                    .addComponent(sure)
                    .addComponent(ButtonCikis)
                    .addComponent(TextSure)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(LabelSure))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCikisActionPerformed
        MainMenu.sutun = 0;
        MainMenu.gosterilecekSutun = 0;
        MainMenu.miktar = 0;
        Business.sure = 0;
        ThreadOrnek.result.clear();
        
        MainMenu mainMenu = new MainMenu();
        setVisible(false);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_ButtonCikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultDoubleFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultDoubleFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultDoubleFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultDoubleFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultDoubleFilter dialog = new ResultDoubleFilter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCikis;
    private javax.swing.JLabel LabelSure;
    private javax.swing.JLabel TextSure;
    private javax.swing.JLabel Veri_sayisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sure;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}
